schema_version = "1.0.0"

id = "layer_comp"
version = "1.0.0"
name = "LayerComp"
tagline = "Layer-based compositing tool, similar to After Effects"
maintainer = "KEN <kken498@gmail.com>"
type = "add-on"
tags = [
    "Compositng",
    "Node",
    "Render",
    "Pipeline"
]
blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Import/Export Blend file from/to disk"
